version: '3.3'
services:
  web:
    image: herlesinc/odoo13:1.0
    container_name: odoo13_web
    domainname: odoo13_web.local
    hostname: odoo13_web
    networks:
      net:
        ipv4_address: 11.11.11.11
    volumes:
      - ./addons:/mnt/extra-addons/
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./autostart.sh:/mnt/extra-addons/autostart.sh
      - odoo-web-data:/var/lib/odoo/odoo13
    restart: always
    stdin_open: true
    tty: true
    command: "/mnt/extra-addons/autostart.sh"
volumes:
  odoo-web-data:
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.11.0/24
