version: '3.3'
services:
  web:
    image: herlesinc/odoo10ce:1.1
    container_name: samu_web_10
    hostname: samu_web_10
    networks:
      net:
        ipv4_address: 10.11.3.10
    ports:
      - "6069:8069"
      - "6068:7068"
    volumes:
      - ./addons:/mnt/extra-addons/
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./autostart.sh:/mnt/extra-addons/autostart.sh
      - odoo-web-data:/var/lib/odoo
    restart: always
    stdin_open: true
    tty: true
    command: "/mnt/extra-addons/autostart.sh"
volumes:
  odoo-web-data:
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.11.3.0/24
